### ISSUE TITLE
--download option does not work

### ISSUE THREAD

**Issue by stennie** [jdrumgoole/gdelttools#3]
I'm following the README and when I try to use the `--download` option there's an error about missing position arg

```
    download_zips(input_file_list)
TypeError: download_zips() missing 1 required positional argument: 'file_list'
```

The `download_zips()` method expects a `collection` as a first argument:
https://github.com/jdrumgoole/gdelttools/blob/bb84a176fcb2231bf96aa190759c89498780598a/gdelttools/gdeltloader.py#L22

... but `--download` only provides the second file list arg

https://github.com/jdrumgoole/gdelttools/blob/bb84a176fcb2231bf96aa190759c89498780598a/gdelttools/gdeltloader.py#L127

**Comment by stennie** [comment]
`mapgeolocation.py` uses `events_csv` as the default collection, so this seems like the expected value

**Comment by jdrumgoole** [comment]
Works in the new package https://pypi.org/project/gdelttools/
